name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 9
      - name: Vitest
        run: pnpm test
  